Add the certificate application using PowerDNS and an HTTP request.
usual2970/certimate pull request #221
Opened 2024-10-19 14:49 UTC by aazf

2024-10-19 15:27 UTC, fudiwei commented
> 建议忽略ui/dist目录，这目录不应该CI自动生成吗？

#122

2024-10-19 22:23 UTC, usual2970 commented
> 建议忽略ui/dist目录，这目录不应该CI自动生成吗？

看来这点的争议一直都在😅，我们可以先不考虑纯后端开发的情况，忽略掉 dist

2024-10-19 22:24 UTC, usual2970 requested changes
Github Actions 也调整一下

2024-10-20 01:34 UTC, usual2970 commented
> 个人看法，这些自动编译的文件，如果不做处理很容易引入安全问题，并且不容易审计。 在Actions里面更不应该信赖预编译文件，所有都应该由源码生成，不然不会出现版本不一致的情况吗？

是的，所以Actions里也由源码生成，你现在只在Dockfile里改了，打包二进制文件也要加前端build步骤

2024-10-20 01:45 UTC, usual2970 commented
> 需要在这个PR里面处理吗？还是你另外处理？

我来处理吧👌

2024-10-20 05:01 UTC, usual2970 approved these changes
细节我来调整吧

2024-10-20 05:02 UTC, merged